.PHONY: clean All

All:
	@echo "----------Building project:[ lc33 - Debug ]----------"
	@cd "lc33" && "$(MAKE)" -f  "lc33.mk"
clean:
	@echo "----------Cleaning project:[ lc33 - Debug ]----------"
	@cd "lc33" && "$(MAKE)" -f  "lc33.mk" clean
